### ISSUE TITLE
Make the 'compile' button also place the widget in deployment folder

### ISSUE THREAD

**Issue by Rvthof** [mendix/WDPForBrackets#1]
When pressing the 'Run/compile' button, it would be really nice to also have it place the new widget code in the deployment folder (and subsequently remove widgets.js so that the original file is used).

**Comment by GREdens** [comment]
Nice one.. :+1:

**Comment by GREdens** [comment]
We are making progress in using mxbuild for that. We need to wrap this up for a next version.

**Comment by GREdens** [comment]
This is moved to the official backlog: https://trello.com/c/NFqJsCAr/18-deploy-widgets-directly-from-wdpforbrackets-in-mendix
