### ISSUE TITLE
Add the option to configure your source in the bottom panel for live preview

### ISSUE THREAD

**Issue by ahagens** [mendix/WDPForBrackets#12]
To accommodate for users that do no always use http://localhost:8080/ a settings button may be added to the bottom panel to configure this.

**Comment by GREdens** [comment]
Thank you for this feedback it is one of the points on our roadmap.

**Comment by GREdens** [comment]
We have put this request on the roadmap, together with the option to "Define a production and a test environment." An "AppStoreWidgetBoilerplate" is designed to run standalone with brackets and will need manual actions to put the widget MPK file from the test project into a production environment. 

By a production environment we mean a teamserver project you create with the Mendix cloud portal / Mendix modeler. 

We intend to change this working process to make it configurable to deploy both the AppStoreWidgetBoilerplate test mendix application and production Mendix application environment from Adobe Brackets. 

And also make this configurable. Your request is now officially on the roadmap of the WDPForBrackets plugin.
