### ISSUE TITLE
Don't open the preview window on startup brackets

### ISSUE THREAD

**Issue by Rvthof** [mendix/WDPForBrackets#13]
I use my brackets for a lot of other things besides Mendix widgets and it is getting annoying having to close the Mendix Preview (which I already don't use anyway) on startup.

**Comment by GREdens** [comment]
Good point.. we will at it to the roadmap.

**Comment by GREdens** [comment]
Moved this issue to the backlog at trello.com: https://trello.com/b/6Z71EPtW/widget-development-plugin-for-brackets-roadmap
