### ISSUE TITLE
Get struck on 25% creating my first widget

### ISSUE THREAD

**Issue by jugarin-golf** [mendix/WDPForBrackets#18]
Hi there,
   I'm Jugarin. I tried to do step by step creating my first widget for Mendix but I've got problem after I provided the widget information (Author, License, etc.) and click OK button.The progress bar has been shown with 25% and struck with it. 
  How can I fix it? 

  Thank you.  

![struck25](https://cloud.githubusercontent.com/assets/13485396/10660866/5ae7be52-78d4-11e5-892a-8c6e0976211d.png)

**Comment by JelteMX** [comment]
This is a copy of the answer on the forum: https://mxforum.mendix.com/questions/8983/Adobe-Brackets--fail-to-create-new-widget#13406
1. Have you followed the basic constraints for the widget? https://world.mendix.com/display/public/howto50/Creating+a+Basic+Hello+World+Custom+Widget#CreatingaBasicHelloWorldCustomWidget-3.CreatingaCustomWidgetwithAdobeBrackets

> The author, license, package name, and name should only contain a-z and A-Z characters. 
> The copyright should only contain a-z , A-Z and 0-9 characters. 
> The version should only contain 0-9 and / or a . characters. 
> The location should only contain a valid directory path.
1. If this doesn't help, please provide a log so we can see where the problem occurs:
- Go to Debug > Show Developer Tools
- In the Developer Tools, open the Console and leave that open
- Now create the widget using the MX Plugin
- If it fails or stalls at 25%, please check the console and see if there any errors. The brackets plugin should provide output on the console, starting with:

_MendixGitHubManager.js:xxx nameOfWidget: PackageName - directoryOfWidget:_

or

_[node-log xx:xx:xx]_

Please provide that log so we can see where it fails

**Comment by jugarin-golf** [comment]
Hi JelteMx,
  I've followed your instruction and I've got this log;

``` []
MendixGitHubManager.js:180 nameOfWidget: MyFirstWidget - directoryOfWidget: D:/Projects/Mendix/MyFirstPackage
MendixGitHubManager.js:240 [mendix.wdpforbrackets-github-getUserRepos]
MendixGitHubManager.js:237 [mendix.wdpforbrackets-github-getUser] failed to run GitHub.getUser -  Object {}
MendixGitHubManager.js:237 (anonymous function)
thirdparty.min.js:556 j
thirdparty.min.js:556 k.fireWith
/utils/NodeConnection.js:498 NodeConnection._receive
```

**Comment by JelteMX** [comment]
Alright, I have checked this error and this seems to do with the Github API. In your response I don't see an error, but I have reproduced this:

`[mendix.wdpforbrackets-github-getUser] failed to run GitHub.getUser -`
`Object {message: "API rate limit exceeded for xxx.xxx.xxx.xxx. (But her…t. Check out the documentation for more details.)", statusCode: 403, headers: Object}headers: Objectmessage: "API rate limit exceeded for xxx.xxx.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"statusCode: 403
`

I'll have to check the code to see what we can do about this. From what I see it checks the `mendix`user and then the repository of the Boilerplate to get the latest version... 

Here's the documentation on Rate limits: https://developer.github.com/v3/#rate-limiting

> Unauthenticated requests are associated with your IP address, and not the user making requests. 

So either we implement a Github authentication or circumvent the user lookup part.

**Comment by jugarin-golf** [comment]
Thank you for your response,  JetleMX.

**Comment by JelteMX** [comment]
No problem @jugarin-golf, I'll see what I can do. We will try to implement an [access token](https://help.github.com/articles/creating-an-access-token-for-command-line-use/) in the plugin, that would solve the rate limit problem. I hope to update it soon. 

In the meantime, are you able to use the Boilerplate itself? If you clone the boilerplate and change the values yourself (name, version, etc), you can point the brackets plugin to the `src` folder, that will make it work as well

**Comment by jugarin-golf** [comment]
Yes, thanks. I will try as your suggestion. @JelteMX
