### ISSUE TITLE
Unclear error when initial directory is incorrect when creating new widget

### ISSUE THREAD

**Issue by ako** [mendix/WDPForBrackets#3]
I pointed to a non existent location: project/widgets/<non_existent_widget_folder> and the plugin complained with: We could not clone the AppStoreBoilerPlate. ENOENT, no such file or directory.

i assumed the file or directory of what needed to be cloned was non existent...

Next i tried setting the location to: project/widgets/ hoping the plugin would create the required folder, but it complained the folder was not empty.

**Comment by GREdens** [comment]
Good on, it should create a none existing directory. Thank you. We will implement this.

**Comment by GREdens** [comment]
This is fixed with the latest version.
