### ISSUE TITLE
Package mendix widget create incorrect file WidgetName.mpk

### ISSUE THREAD

**Issue by ako** [mendix/WDPForBrackets#4]
Should replace WidgetName with the actual widget name.

**Comment by ako** [comment]
Seems caused by the fact that i didn't "save all". Apparently the small dot in front of the file name indicates that it hasn't been saved, and the user isn't notified of this fact when running "Create package"...

**Comment by ako** [comment]
Sorry, too soon. The info balloon in brackets says "You have successfully created an mpk ..... PdfViewer.mpk", but the actual file is called WidgetName.mpk.

**Comment by GREdens** [comment]
I will look into this. But it is important to know all the steps you did. The renaming if files and folders and content is if i read this not bullet proof and can be better. But for that i need all the steps you did.

**Comment by GREdens** [comment]
Should be fixed with the latest version of the plugin.
