### ISSUE TITLE
Automatically add widget package to widgets folder of my mendix project

### ISSUE THREAD

**Issue by ako** [mendix/WDPForBrackets#5]
I've created the widget source project in project/widgets/<widgetname>/....
Would be nice if the generated mpk was automatically placed in project/widgets/... so i just have to refresh my project to see the result. (and call the admin api to restart the runtime ;-)

**Comment by GREdens** [comment]
Thank you for this input. It is very helpful to create a better User Experience. I will look into what is possible to solve this.

**Comment by GREdens** [comment]
We have made progress in using mxbuild for this.. still need to wrap this up in the plugin.

**Comment by GREdens** [comment]
We have moved this request to the official backlog of the application: https://trello.com/b/6Z71EPtW/widget-development-plugin-for-brackets-roadmap
Progress in what will be picked up can be found there. And what is sech
